### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by IntegerLimit** [IntegerLimit/lifesteal-mod#1]
In this order:
- [ ] Warning when you are mining or placing blocks in the spawn protection zone
- [ ] Crafting recipes for hearts, and ultimate hearts
- [ ] Revive Items and Logic
- [ ] Enchantment books above creative levels
